# File automatically generated by build.rs.
# Changes made to this file will not be saved.
from typing import List, Tuple, Any, Optional, Union, ClassVar
import numpy


def read_skel(path: str) -> SkelData: ...


def calculate_relative_transform(
    world_transform: numpy.ndarray,
    parent_world_transform: numpy.ndarray) -> numpy.ndarray: ...


class SkelData:
    major_version: int
    minor_version: int
    bones: list[BoneData]

    def __init__(
        self,
        major_version: int = 1,
        minor_version: int = 0,
    ) -> None: ...

    def save(self, path: str) -> None: ...

    def calculate_world_transform(
        self, bone: BoneData) -> numpy.ndarray: ...


class BoneData:
    name: str
    transform: numpy.ndarray
    parent_index: Optional[int]
    billboard_type: BillboardType

    def __init__(
        self,
        name: str,
        transform: numpy.ndarray,
        parent_index: Optional[int] = None,
        billboard_type: BillboardType = BillboardType.Disabled
    ) -> None: ...


class BillboardType:
    name: str
    value: int

    Disabled: ClassVar[BillboardType]
    XAxisViewPointAligned: ClassVar[BillboardType]
    YAxisViewPointAligned: ClassVar[BillboardType]
    Unk3: ClassVar[BillboardType]
    XYAxisViewPointAligned: ClassVar[BillboardType]
    YAxisViewPlaneAligned: ClassVar[BillboardType]
    XYAxisViewPlaneAligned: ClassVar[BillboardType]

    @staticmethod
    def from_value(value: int) -> Optional[BillboardType]: ...

    @staticmethod
    def from_str(value: str) -> Optional[BillboardType]: ...
