[package]
name = "ssbh_data_py"
version = "0.2.5"
authors = ["ScanMountGoat <>"]
edition = "2018"

[dependencies]
ssbh_lib = { version = "0.6", path = "../ssbh_lib"}
ssbh_data = { version = "0.6", path = "../ssbh_lib/ssbh_data"}

[lib]
name = "ssbh_data_py"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.1"
features = ["extension-module"]

[dev-dependencies]
indoc = "1.0"
