[package]
name = "ssbh_data_py"
version = "0.3.4"
authors = ["ScanMountGoat <>"]
edition = "2018"

[dependencies]
ssbh_data = "0.11.0"

[lib]
name = "ssbh_data_py"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13"
features = ["extension-module"]

[dev-dependencies]
indoc = "1.0"
