[package]
name = "ssbh_data_py"
version = "0.2.2"
authors = ["ScanMountGoat <>"]
edition = "2018"

[dependencies]
ssbh_lib = "0.5.0"
ssbh_data = "0.5.0"

[lib]
name = "ssbh_data_py"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.1"
features = ["extension-module"]