[package]
name = "ssbh_data_py"
version = "0.1.0"
authors = ["ScanMountGoat <>"]
edition = "2018"

[dependencies]
ssbh_lib = { git = "https://github.com/ultimate-research/ssbh_lib" }
ssbh_data = { git = "https://github.com/ultimate-research/ssbh_lib" }

[lib]
name = "ssbh_data_py"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.1"
features = ["extension-module"]