[package]
name = "ssbh_data_py"
version = "0.5.1"
authors = ["ScanMountGoat <>"]
edition = "2018"

[dependencies]
ssbh_data = { path = "../../ssbh_lib/ssbh_data" }
pyo3 = { version = "0.15.0", features = ["extension-module"] }
ssbh_data_py_derive = { path = "../ssbh_data_py_derive" }

[lib]
name = "ssbh_data_py"
crate-type = ["rlib", "cdylib"]

[dev-dependencies]
indoc = "1.0"
strum = "0.23.0"

[build-dependencies]
ssbh_data = { path = "../../ssbh_lib/ssbh_data" }
strum = "0.23.0"