[package]
name = "ssbh_data_py"
version = "0.6.1"
authors = ["ScanMountGoat <>"]
edition = "2018"

[dependencies]
ssbh_data = { git = "https://github.com/ultimate-research/ssbh_lib", features=["strum1"] }
pyo3 = { version = "0.15.0", features = ["extension-module"] }
numpy = "0.15.0"
ssbh_data_py_derive = { path = "../ssbh_data_py_derive" }

[lib]
name = "ssbh_data_py"
crate-type = ["rlib", "cdylib"]

[dev-dependencies]
indoc = "1.0"
strum = "0.23.0"

[build-dependencies]
ssbh_data = { git = "https://github.com/ultimate-research/ssbh_lib", features=["strum1"] }
strum = "0.23.0"