[package]
name = "ssbh_data_py"
version = "0.5.0"
authors = ["ScanMountGoat <>"]
edition = "2018"

[dependencies]
ssbh_data = { git = "https://github.com/ultimate-research/ssbh_lib" }
pyo3 = { version = "0.13", features = ["extension-module"] }
ssbh_data_py_derive = { path = "../ssbh_data_py_derive" }

[lib]
name = "ssbh_data_py"
crate-type = ["cdylib"]

[dev-dependencies]
indoc = "1.0"
