[package]
name = "pyi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

[build-dependencies]
ssbh_data_py = { path = "../ssbh_data_py" }