# Build script taken from https://github.com/BenHall-7/ssbh_data_py
# credit for much of this build system goes to hyperjson https://github.com/mre/hyperjson/
name: Package and Publish
on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install maturin
        run: |
          python -m pip install --upgrade pip
          pip install maturin
      
      - name: Build wheel
        run: maturin build --release --no-sdist --strip --interpreter python${{matrix.python_version}}

      # Note: Windows doesn't support glob
      # https://stackoverflow.com/a/52481267/270334
      - name: Install wheels
        if:  matrix.os == 'windows-latest'
        run: pip install --find-links=target\wheels ssbh_data_py

      - name: Install wheels
        if:  matrix.os != 'windows-latest'
        run: pip install target/wheels/ssbh_data_py*.whl

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/wheels/ssbh_data_py*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: PyPi publish
        if: github.event_name == 'release' && github.event.action == 'created'
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI }}
        run: maturin publish --username __token__  --interpreter python${{matrix.python_version}}
